// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"good-review-master/bot"
	"good-review-master/mcpclient"
	"good-review-master/router"
	"good-review-master/telemetry"
)

// Injectors from wire.go:

// initializeApp 是 Wire 的注入点：函数体里只写 wire.Build，实现由
// `go tool wire ./app` 生成到 wire_gen.go（生成物入库，没装 wire 的机器照样能编能跑）。
//
// # 这一行 wire.Build 就是整个依赖图
//
// 顺序由 Wire 按类型自己排，人只声明"谁由谁造"。比如它从
// provideOneBot → provideBotNickname → provideDerivedConfig 这条链看出
// "昵称必须在快照之前取到"——而那原本是代码注释里的一句话。
// 顺序从**阅读顺序**变成了**类型**，于是编译器能替你检查，这是引这套东西换到的主要收益。
//
// 校验：`go tool wire check ./app`。缺 provider 会在生成期报
// "no provider found for X"（不是等到运行期空指针）。
//
// # 这个文件为什么带 build tag
//
// 清单留在这里而不是 providers.go 的包级 var：那样 wire 包会被链进生产二进制，
// 还会多一次包级初始化。带 `wireinject` 标签的文件只在 wire 跑的时候参与构建，
// 所以 provider 函数与生产代码共用一个文件、图的定义却完全不进产物。
//
// # 改完 provider 一定要重跑
//
// 忘了重跑，编译器看到的仍是上一版 wire_gen.go：编译能过，行为停在旧图上。
// 判据是 `git status` 里 wire_gen.go 有没有该有的差异。
func initializeApp(inputs injectorInputs) (*App, error) {
	appLoadedConfig := inputs.Loaded
	client := provideOneBot(appLoadedConfig)
	appBotNickname := provideBotNickname(client)
	server := provideBuiltinImageMCP(appLoadedConfig)
	appBuiltinImageAddr := provideBuiltinImageAddr(server)
	config := provideDerivedConfig(appLoadedConfig, appBotNickname, appBuiltinImageAddr)
	store := provideConfigStore(config)
	snapshot := provideConfigSnapshot(store)
	appPromptPaths := inputs.PromptPaths
	promptConfig, err := providePromptConfig(appPromptPaths)
	if err != nil {
		return nil, err
	}
	llmClient := inputs.LLM
	mcpConf := config.MCPConfig
	context := inputs.Ctx
	manager := mcpclient.New(mcpConf, context)
	routerRouter := router.NewRouter(snapshot, promptConfig, llmClient, client, manager, context)
	botBot := bot.NewBot(snapshot, client, routerRouter)
	serverServer := provideWebServer(snapshot, client)
	string2 := config.MetricsAddr
	registry := telemetry.NewRegistry()
	metricsServer := provideMetricsServer(string2, registry)
	sources := inputs.Sources
	informer := provideConfigInformer(sources, store, appBotNickname, appBuiltinImageAddr)
	observer := providePromptObserver(appPromptPaths, promptConfig, routerRouter)
	app := provideApp(snapshot, promptConfig, llmClient, client, manager, server, routerRouter, botBot, serverServer, metricsServer, informer, observer)
	return app, nil
}
